name: hmesh3
description: A Command-line utility for communicating with Huawei Mesh 3 API

environment:
  sdk: "^3.4.0"
dependencies:
  args: ^2.5.0
  convert: ^3.1.1
  cryptography: ^2.7.0
  html: ^0.15.4
  http: ^1.2.2
